### ISSUE TITLE
ConfigurationBuilders and extensions

### ISSUE THREAD

**Issue by asgerhallas** [d60/Cirqus#42]
Right now there are two ways to implement configuration api... directly in the ConfigurationBuilder and as an extension method to a configuration builder. 

I can see the point in extension methods for external modules adding their own config options, but I don't see why the core config is moved out into extension methods? Are there a good reason for this - that I have just forgotten about? :)

An argument for moving them into the ConfigurationBuilders is discoverability, as they will be highlighted in intellisense. 

Is there a reason not to?

**Comment by mookid8000** [comment]
I initially made them as extension method to verify that it would actually be possible to configure stuff from an extension method. And then I left them there because I contemplated whether the entire `ViewManagerEventDispatcher`-based view system should be moved out into a separate project. But I don't think we should do that (at least not for a while, and maybe never), so there's no reason why they should not be moved into the configuraiton builder.
