### ISSUE TITLE
Possible bug in order of events in ViewManagerEventDispatcher

### ISSUE THREAD

**Issue by ssboisen** [d60/Cirqus#48]
Hi guys,

In the ViewManagerEventDispatcher on line [#112](https://github.com/d60/Cirqus/blob/master/d60.Cirqus/Views/ViewManagerEventDispatcher.cs#L112) you determine the max sequence number in the batch of events by using Max, I assume this is because no ordering of the events are assumed?

However in lin [#221](https://github.com/d60/Cirqus/blob/master/d60.Cirqus/Views/ViewManagerEventDispatcher.cs#L221) in the CatchUpTo method you use events.Last() to get the max global sequence number. The code doesn't sort the events in any of the intermediate code.

So just for consistency sake, is the order of the events expected to be sorted by global sequence number or not?

**Comment by mookid8000** [comment]
They are expected to be in order :) but I guess you are right that the code could be a little more clear about this.

I guess I could have made it an `IOrderedEnumerable` to be slightly more explicit about it, but now that I read about it I actually think that [that would pollute/mislead even more](http://stackoverflow.com/a/8518941/6560).

Another option would be to make it explicitly accept `List<EventData>` or some other ordered implementation, but that would remove the ability to stream events in some cases (although that might not actually be the case in [the Dispatch method in #112 of `ViewManagerEventDispatcher`](https://github.com/d60/Cirqus/blob/master/d60.Cirqus/Views/ViewManagerEventDispatcher.cs#L112))

PS: Dude - get a book to read instead of reading code.... you are weird :D
PPS: `<seriously>` - I love that you ponder the details like this - keep it coming!
