### ISSUE TITLE
Cirqus.MongoDB - out of date reference to Mongo driver NuGet

### ISSUE THREAD

**Issue by mcquiggd** [d60/Cirqus#73]
Hi guys,

I was updating an example demo of Cirqus to the latest released NuGet packages, and found that the MongoDB package has a requirement to use an older version of MongoDB.Driver (to reference the type MongoDatabase). 

Unfortunately, that version (v1.10) does not seem to be available on NuGet any more.

Simply updating Cirqus.MongoDB to use mongocsharpdriver v2.2,3

Pulls in 

MongoDB.Driver v2.2.3
MongoDB.Driver.Core v2.2.3
MongoDB.Bson v2.2.3

And then all is well. No conflicts raised, and when referenced in sample applications, they perform as expected.

David

**Comment by mookid8000** [comment]
???

I'm puzzled :confused: 

1. [mongocsharpdriver 1.10 does not seem to be unlisted](https://www.nuget.org/packages/mongocsharpdriver/1.10.0)
1. Since Cirqus' MongoDB package is written for versions 1.* of the driver, and the driver has received significant API changes in version 2.*, I cannot believe that anything can work with a drop-in update like that

**Comment by mcquiggd** [comment]
Hi,

 well, last night and this morning, I only see 2.x versions of mongocsharpdriver from the standard nuget feed in VS2015. I will clear my NuGet cache and see if that changes...

And yep, 2.x versions seem to be working without problem... so far... I am using the old sqlsug demo application, which uses SQL Server as its Event Store, and Mongo for its Views...

**Comment by mcquiggd** [comment]
Aha.. I had installed the release candidate of Visual Studio 2015 update 2, and bizarrely it removed my NuGet server entries. So probably all it was showing was my local cache. 

I can in fact see version 1.10 of mongocsharpdriver now that I have re-added my NuGet server entries.

I've updated my post above - regarding compatibility with version 2.x of mongocsharpdriver, etc.

**Comment by NKnusperer** [comment]
Just browsed trough the source code and found this odd line: (expression is always false):
https://github.com/d60/Cirqus/blob/master/d60.Cirqus.MongoDb/Views/MongoDbViewManager.cs#L89
Is this somehow intended?

**Comment by mookid8000** [comment]
Yes, it is intentional - for SOME weird reason (and I never bothered to figure out why), the in-mem caching of the current position in the `_cachedPosition` does not work as intended.

The purpose was to save a database lookup once in a while, but since events are dispatched in batches to the view manager anyway, the cost of doing the lookup in `GetPositionFromPersistentCache` (i.e. directly from the database) is negligible.

**Comment by mookid8000** [comment]
Thanks for the code scrutiny btw 😁  👍
