### ISSUE TITLE
Getting ConcurrencyExceptions now every few seconds

### ISSUE THREAD

**Issue by enriquein** [d60/Cirqus#76]
Hi, yesterday we upgraded to 0.67.1 to install the bugfix to the Postgres event source and ever since I've been getting exceptions like this one every few seconds:

    d60.Cirqus.Exceptions.ConcurrencyException: Could not save batch e6c73eef-5664-4161-812b-bcbd508f9cbe containing
    
    389650 - 69fa1219-4620-4998-9399-988bb8065aa8 / 0
    
    to the event store because someone else beat us to it 

I had previosly read through the changelog and I think I remember reading some releases in which you mention that now Cirqus is surfacing more info to the logs. I'm wondering if this is one such case of it. Did this used to happen all the time and I'm just finding out about it now because of the additional logging? Is it generally harmless? I don't think we actually lost any data over this. I have reverted to the previous build we had in production for the time being just in case.

**Comment by mookid8000** [comment]
You are, as you suspect, most likely seeing this because of the increased level of details in the logging. Am I right in assuming that it is logged with the "Warning" level?

As long as it is logged with the "Warning" level, it is only something that you might want to look out for, because it is a sign that you have contention around certain aggregate root instances - so if it happens a lot, you should see if you can somehow serialize commands to those particular aggregate root instances.

If it only happens once in a while, it is perfectly fine 😄

**Comment by enriquein** [comment]
Correct, they are being logged at the information level. I'll take a look at the configuration and also check those events by hand to try and see what's going on. This is a system I inherited and the original programmer is no longer with the company. 
Thanks for clearing this up!

**Comment by mookid8000** [comment]
No problem 😎
