### ISSUE TITLE
EventStore support?

### ISSUE THREAD

**Issue by NKnusperer** [d60/Cirqus#81]
I'am wondering that there is no support for [EventStore (geteventstore.com) ](https://geteventstore.com/ )?
Wouldn't this be a natural fit?

**Comment by mookid8000** [comment]
You would think that it would be a natural fit, but Greg's event store does not support cross-aggregate transactions.

The thing is: Basically, Cirqus gives up some scalability in trade for the ability to have multiple aggregates participate in the same transaction, which essentially can be boiled down to having a central lock somewhere. In this case, it is the optimistic lock on the issuance of global sequence numbers, combined with a unique constraint on it.

In order to implement this, Cirqus requires that the underlying database is capable of enforcing this constraint in combination with the usual (aggregate root ID, sequence number) constraint.

These things allow for guaranteeing that aggregate roots emit events from a known state, even if multiple instances participate in processing a command.

But unfortunately it does not fit with Event Store's eventual consistency, which does not guarantee that all readers (i.e. projections - aggregate roots and views) read events in the same order all the time.
